{% set version = "2.0.0" %}

package:
  name: jupyter_ydoc
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/j/jupyter_ydoc/jupyter_ydoc-{{ version }}.tar.gz
    sha256: 9bb3f4d327d47597d9430358df3d59795899521ca0eb50c799c0236ef4dc177d
  - folder: src
    url: https://github.com/jupyter-server/jupyter_ydoc/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 17e1e62f0dc6cfbe86f80b6e802af537aee229f86d20df1fcbdbffc466ed4d43

build:
  noarch: python
  number: 0
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatch-nodejs-version
    - hatchling >=1.10.0
    - pip
    - python >=3.7
  run:
    - importlib_metadata >=3.6
    - python >=3.7
    - y-py >=0.6.0,<0.7.0

test:
  source_files:
    - src/javascript
    - src/lerna.json
    - src/package.json
    - src/tests
  requires:
    - nodejs >=18,<19
    - pip
    - pytest-asyncio
    - pytest-cov
    - websockets >=10.0
    - yarn <2
    - ypy-websocket >=0.8.3,<0.9.0
    # - mypy
  imports:
    - jupyter_ydoc
  commands:
    - pip check
    - export YARN_CACHE_FOLDER="$SRC_DIR/.yarn-cache"  # [unix]
    - set YARN_CACHE_FOLDER="%SRC_DIR%/.yarn-cache"  # [win]
    - cd src && yarn --frozen-lockfile --ignore-scripts && yarn lerna bootstrap && yarn build && cd ..
    - cd src && pytest -vv --asyncio-mode=auto --cov=jupyter_ydoc --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=70
    # - mypy -p jupyter_ydoc

about:
  home: https://github.com/jupyter-server/jupyter_ydoc
  license: BSD-3-Clause
  license_family: BSD
  license_file: dist/LICENSE
  summary: Document structures for collaborative editing using Ypy
  doc_url: https://jupyter-ydoc.readthedocs.io

extra:
  recipe-maintainers:
    - davidbrochart
    - conda-forge/jupyter_server
