{% set version = "1.1.0" %}

package:
  name: jupyter_ydoc
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/j/jupyter_ydoc/jupyter_ydoc-{{ version }}.tar.gz
    sha256: 6e248c5688420c60a65e4e70d371c234dec2fc8643be829a483d49b128fe6ed6
  - folder: src
    url: https://github.com/jupyter-server/jupyter_ydoc/archive/refs/tags/v{{ version }}.tar.gz
    sha256: aa0664096162bb53b96245b136554cb2eae70ea9ea60a947104260aadb50ee00

build:
  noarch: python
  number: 0
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - hatch-nodejs-version
    - hatchling >=1.10.0
    - pip
    - python >=3.7
  run:
    - importlib_metadata >=3.6
    - python >=3.7
    - y-py >=0.6.0,<0.7.0

test:
  source_files:
    - src/.yarnrc.yml
    - src/javascript
    - src/lerna.json
    - src/package.json
    - src/tests
    - src/yarn.lock
  requires:
    - nodejs >=20,<21
    - pip
    - pytest-asyncio
    - pytest-cov
    - websockets >=10.0
    - yarn >=3,<4
    - ypy-websocket >=0.8.3,<0.9.0
  imports:
    - jupyter_ydoc
  commands:
    - pip check

about:
  home: https://github.com/jupyter-server/jupyter_ydoc
  license: BSD-3-Clause
  license_family: BSD
  license_file: dist/LICENSE
  summary: Document structures for collaborative editing using Ypy
  doc_url: https://jupyter-ydoc.readthedocs.io

extra:
  recipe-maintainers:
    - davidbrochart
    - conda-forge/jupyter_server
