{% set version = "3.0.3" %}
{% set python_min = python_min | default("3.9") %}

package:
  name: jupyter_ydoc
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.org/packages/source/j/jupyter_ydoc/jupyter_ydoc-{{ version }}.tar.gz
    sha256: 66f3d37a9a02a9711b508a5574b0ac489aa40f216030af29fdd82c862a2eb5ea
  - folder: src
    url: https://github.com/jupyter-server/jupyter_ydoc/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 2509e19df2a34401e9aca6a25279dc3e88ac8dc9591a3369c7eb5aad61c49a7f

build:
  noarch: python
  number: 0
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - hatch-nodejs-version
    - hatchling >=1.10.0
    - pip
    - python {{ python_min }}
  run:
    - importlib-metadata >=3.6
    - python >={{ python_min }}
    - pycrdt >=0.10.1,<0.11.0

test:
  source_files:
    - src/javascript
    - src/lerna.json
    - src/package.json
    - src/tests
    - src/yarn.lock
  requires:
    - httpx-ws >=0.5.2
    - hypercorn >=0.16.0
    - nodejs >=22,<23
    - pip
    - pycrdt-websocket >=0.15.0,<0.16.0
    - pytest-asyncio
    - pytest-cov
    - python {{ python_min }}
    - websockets >=10.0
    - yarn <4
  imports:
    - jupyter_ydoc
  commands:
    - pip check
    - export YARN_CACHE_FOLDER="$SRC_DIR/.yarn-cache" || set "YARN_CACHE_FOLDER=%SRC_DIR%/.yarn-cache"
    - cd src
    - 'echo "{nodeLinker: node-modules, enableImmutableInstalls: false}" >> .yarnrc.yml'
    - yarn
    - yarn build
    - coverage run --source=jupyter_ydoc --branch -m pytest -vv --asyncio-mode=auto --color=yes --tb=long
    - coverage report --show-missing --skip-covered --fail-under=81

about:
  home: https://github.com/jupyter-server/jupyter_ydoc
  license: BSD-3-Clause
  license_family: BSD
  license_file: dist/LICENSE
  summary: Document structures for collaborative editing using Ypy
  doc_url: https://jupyter-ydoc.readthedocs.io

extra:
  recipe-maintainers:
    - davidbrochart
    - conda-forge/jupyter_server
