# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "3.0.5"

package:
  name: jupyter_ydoc
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/j/jupyter_ydoc/jupyter_ydoc-${{ version }}.tar.gz
    sha256: 12208841a1edfe8ee16b8be3e843d54090268498de2d2e783c33a5dd33c995ff
    target_directory: dist
  - url: https://github.com/jupyter-server/jupyter_ydoc/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 69a9393204a1dc40798dac385a9aff50601d458c2280679f58a25070e5170987
    target_directory: src

build:
  number: 0
  noarch: python
  script:
    - cd dist
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - hatch-nodejs-version
    - hatchling >=1.10.0
    - pip
    - python ${{ python_min }}.*
  run:
    - importlib-metadata >=3.6
    - python >=${{ python_min }}
    - pycrdt >=0.10.1,<0.13.0

tests:
  - python:
      imports: jupyter_ydoc
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - files:
      recipe:
        - run_test.py
      source:
        - src/javascript/
        - src/lerna.json
        - src/package.json
        - src/tests/
        - src/yarn.lock
    requirements:
      run:
        - httpx-ws >=0.5.2
        - hypercorn >=0.16.0
        - nodejs >=22,<23
        - pycrdt-websocket >=0.15.0,<0.16.0
        - pytest-asyncio
        - pytest-cov
        - python ${{ python_min }}.*
        - websockets >=10.0
        - yarn <4
    script:
      file: run_test.py
      interpreter: python

about:
  license: BSD-3-Clause
  license_file: dist/LICENSE
  summary: Document structures for collaborative editing using Ypy
  homepage: https://github.com/jupyter-server/jupyter_ydoc
  documentation: https://jupyter-ydoc.readthedocs.io

extra:
  recipe-maintainers:
    - davidbrochart
    - conda-forge/jupyter_server
